### ISSUE TITLE
qrencode: option requires an argument -- 'l'

### ISSUE THREAD

**Issue by erickeller** [fukuchi/libqrencode#103] opened 2017-08-30 19:11 UTC
Hi there,

```
cat /etc/os-release
NAME="Ubuntu"
VERSION="17.04 (Zesty Zapus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.04"
VERSION_ID="17.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=zesty
UBUNTU_CODENAME=zesty
dpkg -l qrencode
...
ii  qrencode                    3.4.4-1build1      amd64              QR Code encoder into PNG image
...
```

When using the "-l" (small L) I get the following issue:

```
cat Downloads/foobar.ics | qrencode -l L -S -v 40 -o output.png                                                 
There is no -v option ("less --help" for help)
40: No such file or directory
-o: No such file or directory
output.png  (press RETURN)qrencode: option requires an argument -- 'l'
Try `qrencode --help' for more information.
```

using the long option works well --level L

Cheers

**Comment by fukuchi** [comment] 2017-09-02 04:48
Hello @erickeller,

Thank you for the report. I copied and pasted the options you wrote and it worked perfectly on my Ubuntu 17.04.

It seems strange that it says:

> There is no -v option ("less --help" for help)

This message must be from 'less', not from 'qrencode'. I guess that your qrencode is a shell script and it calls less and qrencode binary. Please check which qrencode is really called from the shell.

**Comment by erickeller** [comment] 2017-09-07 20:10
indeed, I did the same test in some docker images and resulted in the same working behavior...
It was really confusing since it still happend on my main disto :(

And then your comment about less made absolutely sense...

```
alias | grep less                                                                                                      
L='| less'
```

It was an alias in my zsh and strangely enough it completed the -L option of the qrencode short option -L ... I have to take a look at the zsh behavior now.

I think you can close this ticket.

**Comment by fukuchi** [comment] 2017-09-08 13:05
Hmm, sounds strange. I could not reproduce it with my zsh environment. Anyway, this might not be libqrencode's issue. I close this ticket.

**Closed by fukuchi** 2017-09-08 13:05 UTC
